[project]
name = "ASTR513_Midterm_Project.Pink_Fluffy_Unicorns"
version = "1.0"
license = { file = "LICENSE" }
dependencies = [
    "numpy",
    "matplotlib",
    "astropy",
    "scipy",
    "opencv-python",
    "tqdm",
    "Pillow",
    
]
